spring.application.name=kafka
#management.endpoints.web.exposure.include=*
#wsl hostname -I
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=exchange-rate-group
spring.kafka.consumer.topic-name=exchange-rates