spring.application.name=kafka
management.endpoints.web.exposure.include=*
#wsl hostname -I
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=tp-kafka-step1
spring.kafka.consumer.topic-name=mon-tunnel-topic